name: Flutter Windows Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Install the FULL version of Inno Setup to include language files
      - name: Install Inno Setup with Languages
        run: choco install innosetup --params="'/Full'" --no-progress -y

      - name: Install dependencies
        run: flutter pub get

      - name: Verify Flutter installation
        run: flutter doctor -v

      - name: Build Flutter Windows
        run: flutter build windows --release

      - name: Create installer
        run: |
          $issFile = Get-ChildItem -Path . -Filter "*.iss" -Recurse | Select-Object -First 1
          if ($null -eq $issFile) {
            Write-Error "No Inno Setup script (.iss file) found in the repository"
            exit 1
          }
          # The default install path for Inno Setup's compiler
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" $issFile.FullName

      - name: Find installer
        id: find-installer
        run: |
          $installer = Get-ChildItem -Path . -Filter "*.exe" -Recurse | Where-Object { $_.Name -like "*Setup*.exe" } | Select-Object -First 1
          if ($null -eq $installer) {
            Write-Error "No installer file found"
            exit 1
          }
          echo "installer_path=$($installer.FullName)" >> $env:GITHUB_OUTPUT
          echo "installer_name=$($installer.Name)" >> $env:GITHUB_OUTPUT

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: ${{ steps.find-installer.outputs.installer_path }}

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Flutter Windows Desktop Release"
          files: ${{ steps.find-installer.outputs.installer_path }}
          draft: false
          prerelease: false
